import React, { useState, useEffect } from 'react';
import { useAuth } from '../../../contexts/AuthContext';
import { Newspaper, Bot, Calendar } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export default function ExecutiveIntelligenceCenter() {
  const { getToken } = useAuth();
  const [summaries, setSummaries] = useState<any[]>([]);

  useEffect(() => {
    fetchSummaries();
  }, []);

  const fetchSummaries = async () => {
    try {
      const token = await getToken();
      const res = await fetch('/api/v1/intelligence/summaries', {
         headers: { Authorization: `Bearer ${token}` }
      });
      if (res.ok) setSummaries(await res.json());
    } catch(e) { console.error(e); }
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto h-[calc(100vh-8rem)] flex flex-col">
       <div className="shrink-0 flex justify-between items-center">
         <div>
           <h2 className="text-2xl font-black text-slate-800">Executive Summary Engine</h2>
           <p className="text-slate-500">Automated AI narratives summarizing organizational velocity and risks.</p>
         </div>
       </div>

       <div className="flex-1 overflow-y-auto space-y-6">
          {summaries.map((summary) => (
             <div key={summary.id} className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                <div className="bg-slate-900 px-6 py-4 flex items-center justify-between text-white">
                   <div className="flex items-center gap-3">
                      <Newspaper className="w-5 h-5 text-indigo-400" />
                      <h3 className="font-bold">{summary.period} EXECUTIVE BRIEF</h3>
                   </div>
                   <div className="text-xs font-mono text-slate-400 flex items-center gap-1.5">
                      <Calendar className="w-3.5 h-3.5"/>
                      {new Date(summary.createdAt).toLocaleDateString()}
                   </div>
                </div>
                <div className="p-6">
                   <div className="prose prose-slate max-w-none text-sm leading-relaxed">
                      <ReactMarkdown>{summary.summaryText}</ReactMarkdown>
                   </div>
                   <div className="mt-6 pt-4 border-t border-slate-100 flex items-center gap-2 text-[10px] uppercase font-bold text-slate-400 tracking-widest">
                      <Bot className="w-4 h-4"/> GENERATED BY ENTERPRISE INTELLIGENCE ENGINE
                   </div>
                </div>
             </div>
          ))}
          {summaries.length === 0 && (
             <div className="p-12 text-center border-2 border-dashed border-slate-200 rounded-xl">
                 <Newspaper className="w-12 h-12 mx-auto text-slate-300 mb-4" />
                 <h3 className="text-lg font-bold text-slate-600">No Summaries Available</h3>
                 <p className="text-slate-400 text-sm mt-1">Periodic AI summaries have not been generated yet.</p>
             </div>
          )}
       </div>
    </div>
  );
}
